spring.application.name=api.transaccion
#server.servlet.context-path=/api2
server.port=8081

#Configuration for H2 database
spring.datasource.url=jdbc:h2:mem:transaccionesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 console
spring.h2.console.enabled=true

#Secret key
app.security.aes-key=12345678901234567890123456789012

